[pytest]
DJANGO_SETTINGS_MODULE = config.settings.development

markers =
    system: marks tests as full system/integration tests (select with -m system)

filterwarnings =
    ignore::django.utils.deprecation.RemovedInDjango60Warning