import { useState } from 'react'
import useDebateStore from '../../store/debateStore'
import { debateAPI } from '../../services/api'
import { useAuth } from '../../hooks/useAuth'
import Modal from '../ui/Modal'

/**
 * FIXES:
 * [FE-09] sessionHistory now loaded from API (see useAuth.js)
 * [FE-08] handleSessionClick now fetches full session with messages
 * [FE-25] Session titles now shown (from API, auto-generated by backend)
 * [FE-22] Delete button added to each session item
 * [FE-16] New sessions appear immediately (prependSession in ChatPage)
 */
export default function Sidebar({ isOpen, onClose, onNewSession }) {
  const { isAuthenticated } = useAuth()
  const {
    sessionHistory,
    removeSessionFromHistory,
    currentSessionId,
    loadSession,
  } = useDebateStore()

  const [loadingSessionId, setLoadingSessionId] = useState(null)
  const [deletingSessionId, setDeletingSessionId] = useState(null)
  const [confirmDeleteId, setConfirmDeleteId] = useState(null)

  const STAGE_LABELS = {
    existence:   'Existence of God',
    prophethood: 'Prophethood',
    muhammad:    'Muhammad ﷺ',
    invitation:  'Invitation to Islam',
  }

  /**
   * FIX [FE-08]: Fetch full session data (including messages) before loading.
   * Previously called loadSession(session) with the list item (no messages).
   */
  const handleSessionClick = async (session) => {
    if (session.id === currentSessionId) {
      onClose()
      return
    }

    setLoadingSessionId(session.id)
    try {
      const { data: fullSession } = await debateAPI.getSession(session.id)
      loadSession(fullSession)
      onClose()
    } catch (err) {
      console.error('Failed to load session:', err)
    } finally {
      setLoadingSessionId(null)
    }
  }

  const handleNewSession = () => {
    onNewSession()
    onClose()
  }

  const handleDeleteClick = (e, sessionId) => {
    e.stopPropagation()
    setConfirmDeleteId(sessionId)
  }

  const handleConfirmDelete = async () => {
    if (!confirmDeleteId) return
    setDeletingSessionId(confirmDeleteId)
    setConfirmDeleteId(null)

    try {
      await debateAPI.deleteSession(confirmDeleteId)
      removeSessionFromHistory(confirmDeleteId)
    } catch (err) {
      console.error('Failed to delete session:', err)
    } finally {
      setDeletingSessionId(null)
    }
  }

  return (
    <>
      {/* Mobile overlay */}
      {isOpen && (
        <div style={styles.overlay} onClick={onClose} />
      )}

      <aside style={styles.sidebar(isOpen)}>
        {/* Header */}
        <div style={styles.header}>
          <span style={styles.logo}>📖 DoesGodExist.ai</span>
          <button style={styles.closeBtn} onClick={onClose}>✕</button>
        </div>

        {/* New debate button */}
        <button style={styles.newBtn} onClick={handleNewSession}>
          + New Debate
        </button>

        {/* Session history */}
        <div style={styles.historySection}>
          <p style={styles.historyLabel}>
            {isAuthenticated ? 'Your Debates' : 'Sign in to save debates'}
          </p>

          {/* FIX: sessionHistory is now populated from API */}
          {sessionHistory.length === 0 && isAuthenticated && (
            <p style={styles.emptyText}>No debates yet. Start one!</p>
          )}

          {sessionHistory.map((session) => (
            <div
              key={session.id}
              style={styles.sessionItem(session.id === currentSessionId)}
              onClick={() => handleSessionClick(session)}
            >
              <div style={styles.sessionContent}>
                <p style={styles.sessionTitle}>
                  {loadingSessionId === session.id
                    ? 'Loading...'
                    : (session.title || 'Debate Session')}
                </p>
                <p style={styles.sessionMeta}>
                  {STAGE_LABELS[session.current_stage] || session.current_stage}
                  {session.total_turns > 0 && ` · ${session.total_turns} turns`}
                </p>
              </div>

              {/* DELETE BUTTON */}
              <button
                style={styles.deleteBtn(deletingSessionId === session.id)}
                onClick={(e) => handleDeleteClick(e, session.id)}
                disabled={deletingSessionId === session.id}
                title="Delete this debate"
              >
                {deletingSessionId === session.id ? '...' : '🗑'}
              </button>
            </div>
          ))}
        </div>

        {/* Bottom links */}
        <div style={styles.footer}>
          <a
            href="https://stripe.com"   // Replace with your Stripe link
            target="_blank"
            rel="noopener noreferrer"
            style={styles.supportBtn}
          >
            ♥ Support this project
          </a>
        </div>
      </aside>

      {/* Confirm delete modal */}
      <Modal
        isOpen={!!confirmDeleteId}
        title="Delete Debate?"
        message="This debate and all its messages will be deleted. This cannot be undone."
        confirmLabel="Delete"
        cancelLabel="Cancel"
        onConfirm={handleConfirmDelete}
        onCancel={() => setConfirmDeleteId(null)}
        destructive
      />
    </>
  )
}

const styles = {
  overlay: {
    position: 'fixed', inset: 0,
    background: 'rgba(0,0,0,0.5)',
    zIndex: 99,
  },
  sidebar: (isOpen) => ({
    position: 'fixed',
    left: 0, top: 0, bottom: 0,
    width: 280,
    background: '#13151e',
    borderRight: '1px solid #2a2d38',
    display: 'flex',
    flexDirection: 'column',
    transform: isOpen ? 'translateX(0)' : 'translateX(-100%)',
    transition: 'transform 0.25s ease',
    zIndex: 100,
    overflowY: 'auto',
  }),
  header: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '16px',
    borderBottom: '1px solid #2a2d38',
  },
  logo: { color: '#d4a853', fontWeight: 600, fontSize: 14 },
  closeBtn: {
    background: 'none', border: 'none',
    color: '#8b8fa8', cursor: 'pointer', fontSize: 16,
  },
  newBtn: {
    margin: 12,
    padding: '10px 16px',
    background: '#d4a853',
    border: 'none',
    borderRadius: 8,
    color: '#0f1117',
    fontWeight: 600,
    cursor: 'pointer',
    fontSize: 14,
  },
  historySection: {
    flex: 1,
    padding: '0 8px',
    overflowY: 'auto',
  },
  historyLabel: {
    color: '#555',
    fontSize: 11,
    fontWeight: 600,
    textTransform: 'uppercase',
    letterSpacing: 1,
    padding: '8px 8px 4px',
    margin: 0,
  },
  emptyText: {
    color: '#555',
    fontSize: 13,
    padding: '12px 8px',
    margin: 0,
  },
  sessionItem: (isActive) => ({
    display: 'flex',
    alignItems: 'center',
    padding: '10px 8px',
    borderRadius: 8,
    cursor: 'pointer',
    marginBottom: 2,
    background: isActive ? '#1e2130' : 'transparent',
    border: isActive ? '1px solid #2a2d38' : '1px solid transparent',
    transition: 'background 0.15s',
  }),
  sessionContent: { flex: 1, minWidth: 0 },
  sessionTitle: {
    color: '#e8e9ef',
    fontSize: 13,
    fontWeight: 500,
    margin: '0 0 2px',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  sessionMeta: {
    color: '#555',
    fontSize: 11,
    margin: 0,
  },
  deleteBtn: (loading) => ({
    background: 'none',
    border: 'none',
    color: loading ? '#555' : '#8b8fa8',
    cursor: loading ? 'not-allowed' : 'pointer',
    padding: '4px',
    fontSize: 14,
    flexShrink: 0,
    opacity: loading ? 0.5 : 0.6,
  }),
  footer: {
    padding: '12px 16px',
    borderTop: '1px solid #2a2d38',
  },
  supportBtn: {
    display: 'block',
    textAlign: 'center',
    padding: '8px',
    background: '#1e2130',
    borderRadius: 8,
    color: '#d4a853',
    textDecoration: 'none',
    fontSize: 13,
    fontWeight: 500,
  },
}
