# Generated by Django 5.2.12 on 2026-03-07 10:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('is_anonymous_user', models.BooleanField(default=False)),
                ('tier', models.CharField(choices=[('anonymous', 'Anonymous'), ('registered', 'Registered'), ('premium', 'Premium')], default='anonymous', max_length=20)),
                ('preferred_language', models.CharField(choices=[('en', 'English'), ('ar', 'Arabic'), ('ur', 'Urdu')], default='en', max_length=5)),
                ('daily_turn_count', models.IntegerField(default=0)),
                ('daily_reset_date', models.DateField(blank=True, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DebateSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_stage', models.CharField(choices=[('existence', 'Existence of God'), ('prophethood', 'Prophethood'), ('muhammad', 'Muhammad SAW'), ('invitation', 'Invitation to Islam')], default='existence', max_length=30)),
                ('debate_mode', models.CharField(choices=[('standard', 'Standard'), ('scientific', 'Scientific'), ('philosophical', 'Philosophical'), ('reflective', 'Reflective'), ('comparative', 'Comparative Religions'), ('prophethood_mode', 'Prophethood Mode')], default='standard', max_length=30)),
                ('detected_persona', models.CharField(blank=True, choices=[('skeptic', 'Skeptic'), ('seeker', 'Seeker'), ('academic', 'Academic')], max_length=20, null=True)),
                ('god_acceptance', models.BooleanField(null=True)),
                ('prophecy_acceptance', models.BooleanField(null=True)),
                ('muhammad_acceptance', models.BooleanField(null=True)),
                ('complexity_score', models.FloatField(default=0.0)),
                ('total_tokens', models.IntegerField(default=0)),
                ('total_cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=10)),
                ('content', models.TextField()),
                ('stage', models.CharField(max_length=30)),
                ('token_count', models.IntegerField(default=0)),
                ('retrieved_chunk_ids', models.JSONField(default=list)),
                ('citations', models.JSONField(default=list)),
                ('is_fallacy_detected', models.BooleanField(default=False)),
                ('fallacy_types', models.JSONField(default=list)),
                ('sequence_num', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='debate_app.debatesession')),
            ],
            options={
                'ordering': ['sequence_num'],
            },
        ),
        migrations.CreateModel(
            name='PromptTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage', models.CharField(max_length=30)),
                ('version', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('system_template', models.TextField()),
                ('context_template', models.TextField()),
                ('tone', models.CharField(choices=[('logical', 'Logical'), ('scientific', 'Scientific'), ('reflective', 'Reflective'), ('philosophical', 'Philosophical')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('stage', 'version')},
            },
        ),
        migrations.AddIndex(
            model_name='debatesession',
            index=models.Index(fields=['user', 'current_stage', 'created_at'], name='debate_app__user_id_4df4f4_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['session', 'sequence_num'], name='debate_app__session_c8dbb6_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['session', 'stage'], name='debate_app__session_648457_idx'),
        ),
    ]
