# Generated by Django 5.2.12 on 2026-03-10 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('debate_app', '0002_alter_user_email'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='debatesession',
            name='debate_app__user_id_4df4f4_idx',
        ),
        migrations.AddField(
            model_name='debatesession',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='debatesession',
            name='total_turns',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='last_active_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='debatesession',
            name='total_cost_usd',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='message',
            unique_together={('session', 'sequence_num')},
        ),
        migrations.AddIndex(
            model_name='debatesession',
            index=models.Index(fields=['user', 'deleted_at', 'created_at'], name='debate_app__user_id_dbf353_idx'),
        ),
        migrations.AddIndex(
            model_name='debatesession',
            index=models.Index(fields=['user', 'current_stage'], name='debate_app__user_id_d70546_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['session', 'role'], name='debate_app__session_3182d6_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['session_key'], name='debate_app__session_d97d53_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['tier', 'daily_reset_date'], name='debate_app__tier_ec9a6d_idx'),
        ),
    ]
