# Generated by Django 5.2.12 on 2026-03-07 10:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GPTLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model_used', models.CharField(max_length=64)),
                ('routing_reason', models.CharField(default='', max_length=100)),
                ('prompt_tokens', models.IntegerField()),
                ('completion_tokens', models.IntegerField()),
                ('total_tokens', models.IntegerField()),
                ('cost_usd', models.DecimalField(decimal_places=6, max_digits=8)),
                ('latency_ms', models.IntegerField()),
                ('prompt_hash', models.CharField(default='', max_length=64)),
                ('cache_layer', models.CharField(blank=True, max_length=10, null=True)),
                ('cache_hit', models.BooleanField(default=False)),
                ('error', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BudgetAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('month', models.DateField()),
                ('total_cost_usd', models.DecimalField(decimal_places=4, max_digits=8)),
                ('alert_level', models.CharField(choices=[('50pct', '50%'), ('80pct', '80%'), ('100pct', '100%')], max_length=10)),
                ('is_cutoff_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('month', 'alert_level')},
            },
        ),
    ]
