# Generated by Django 5.2.12 on 2026-03-07 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics_app', '0001_initial'),
        ('debate_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gptlog',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='debate_app.message'),
        ),
        migrations.AddField(
            model_name='gptlog',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gpt_logs', to='debate_app.debatesession'),
        ),
        migrations.AddIndex(
            model_name='gptlog',
            index=models.Index(fields=['created_at'], name='analytics_a_created_79441a_idx'),
        ),
        migrations.AddIndex(
            model_name='gptlog',
            index=models.Index(fields=['session'], name='analytics_a_session_3502da_idx'),
        ),
    ]
