# Generated by Django 5.2.12 on 2026-03-11 03:44

import django.contrib.postgres.fields
import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        # pgvector extension must exist before VectorField can be created
        ('rag_app', '0000_create_pgvector_extension'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=512)),
                ('source_type', models.CharField(choices=[('quran', 'Quran'), ('hadith', 'Hadith'), ('philosophy', 'Philosophy / Rational Arguments'), ('scientific', 'Scientific Signs'), ('comparative_religion', 'Comparative Religion'), ('logic', 'Logic / Reasoning Framework'), ('meta', 'Meta / Debate Topics / Glossary')], max_length=30)),
                ('author', models.CharField(blank=True, max_length=256, null=True)),
                ('checksum', models.CharField(max_length=64, unique=True)),
                ('indexing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('complete', 'Complete'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('chunk_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chunk_index', models.IntegerField()),
                ('content', models.TextField()),
                ('content_arabic', models.TextField(blank=True, null=True)),
                ('content_urdu', models.TextField(blank=True, null=True)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True)),
                ('token_count', models.IntegerField()),
                ('chunk_type', models.CharField(max_length=30)),
                ('stage_tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=list, size=None)),
                ('topic_tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=list, size=None)),
                ('source_ref', models.JSONField(default=dict)),
                ('embedding_model', models.CharField(default='text-embedding-3-small', max_length=64)),
                ('embedding_version', models.IntegerField(default=1)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chunks', to='rag_app.document')),
            ],
            options={
                'ordering': ['chunk_index'],
                'indexes': [models.Index(fields=['chunk_type', 'embedding_version'], name='rag_app_doc_chunk_t_5a0f9b_idx'), models.Index(fields=['is_verified', 'deleted_at'], name='rag_app_doc_is_veri_758681_idx')],
            },
        ),
    ]