# Generated by Django 5.2.12 on 2026-03-11 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag_app', '0002_alter_documentchunk_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentchunk',
            name='embedding_dim',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
