from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.db import models
from uuid import uuid4


class UserManager(BaseUserManager):
    def create_user(self, email=None, password=None, **extra):
        if email:
            email = self.normalize_email(email)
        user = self.model(email=email, **extra)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password, **extra):
        extra.update({'is_staff': True, 'is_superuser': True})
        return self.create_user(email, password, **extra)


class User(AbstractBaseUser, PermissionsMixin):
    id = models.UUIDField(primary_key=True, default=uuid4, editable=False)

    # FIX: Remove default='' — blank email is handled by null=True, blank=True
    email = models.EmailField(unique=True, null=True, blank=True)
    session_key = models.CharField(max_length=64, null=True, blank=True, db_index=True)
    is_anonymous_user = models.BooleanField(default=False)

    tier = models.CharField(
        max_length=20,
        choices=[('anonymous', 'Anonymous'), ('registered', 'Registered'), ('premium', 'Premium')],
        default='anonymous'
    )
    preferred_language = models.CharField(
        max_length=5,
        choices=[('en', 'English'), ('ar', 'Arabic'), ('ur', 'Urdu')],
        default='en'
    )
    daily_turn_count = models.IntegerField(default=0)
    daily_reset_date = models.DateField(null=True, blank=True)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    last_active_at = models.DateTimeField(null=True, blank=True)  # NEW
    deleted_at = models.DateTimeField(null=True, blank=True)
    metadata = models.JSONField(default=dict)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []
    objects = UserManager()

    class Meta:
        indexes = [
            models.Index(fields=['session_key']),
            models.Index(fields=['tier', 'daily_reset_date']),  # NEW: for reset task
        ]

    def __str__(self):
        return self.email or f'anon:{self.session_key}'


class DebateSession(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid4, editable=False)
    user = models.ForeignKey(User, on_delete=models.PROTECT, db_index=True,
                             related_name='sessions')

    # FIX: Add title field (auto-generated by Celery task)
    title = models.CharField(max_length=200, null=True, blank=True)

    current_stage = models.CharField(
        max_length=30,
        choices=[
            ('existence', 'Existence of God'),
            ('prophethood', 'Prophethood'),
            ('muhammad', 'Muhammad SAW'),
            ('invitation', 'Invitation to Islam'),
        ],
        default='existence'
    )
    debate_mode = models.CharField(
        max_length=30,
        choices=[
            ('standard', 'Standard'),
            ('scientific', 'Scientific'),
            ('philosophical', 'Philosophical'),
            ('reflective', 'Reflective'),
            ('comparative', 'Comparative Religions'),
            ('prophethood_mode', 'Prophethood Mode'),
        ],
        default='standard'
    )
    detected_persona = models.CharField(
        max_length=20,
        choices=[('skeptic', 'Skeptic'), ('seeker', 'Seeker'), ('academic', 'Academic')],
        null=True, blank=True
    )
    god_acceptance = models.BooleanField(null=True)
    prophecy_acceptance = models.BooleanField(null=True)
    muhammad_acceptance = models.BooleanField(null=True)

    # FIX: complexity_score is now written by orchestrator
    complexity_score = models.FloatField(default=0.0)

    # NEW: track total round-trips for front-end display
    total_turns = models.IntegerField(default=0)

    total_tokens = models.IntegerField(default=0)
    total_cost_usd = models.DecimalField(max_digits=10, decimal_places=6, default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    completed_at = models.DateTimeField(null=True, blank=True)
    deleted_at = models.DateTimeField(null=True, blank=True)
    metadata = models.JSONField(default=dict)

    class Meta:
        indexes = [
            models.Index(fields=['user', 'deleted_at', 'created_at']),
            models.Index(fields=['user', 'current_stage']),
        ]

    def __str__(self):
        return f'Session({self.user}) Stage:{self.current_stage}'


class Message(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid4, editable=False)
    session = models.ForeignKey(DebateSession, on_delete=models.CASCADE,
                                related_name='messages')
    role = models.CharField(max_length=10,
                            choices=[('user', 'User'), ('assistant', 'Assistant')])
    content = models.TextField()
    stage = models.CharField(max_length=30)
    token_count = models.IntegerField(default=0)
    retrieved_chunk_ids = models.JSONField(default=list)
    citations = models.JSONField(default=list)
    is_fallacy_detected = models.BooleanField(default=False)
    fallacy_types = models.JSONField(default=list)
    sequence_num = models.IntegerField()
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        indexes = [
            models.Index(fields=['session', 'sequence_num']),
            models.Index(fields=['session', 'stage']),
            models.Index(fields=['session', 'role']),
        ]
        # FIX: Prevents duplicate sequence_num under concurrency
        unique_together = [['session', 'sequence_num']]
        ordering = ['sequence_num']


class PromptTemplate(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid4, editable=False)
    stage = models.CharField(max_length=30)
    version = models.IntegerField()
    is_active = models.BooleanField(default=True)
    system_template = models.TextField()
    context_template = models.TextField()
    tone = models.CharField(max_length=30,
        choices=[('logical', 'Logical'), ('scientific', 'Scientific'),
                 ('reflective', 'Reflective'), ('philosophical', 'Philosophical')])
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = [['stage', 'version']]
        # FIX: Only ONE active template per stage at a time
        # (enforced in application logic — see prompt_builder.py fix)